### ISSUE TITLE
[Request] Can you make a cordova plugin also?

### ISSUE THREAD

**Issue by gaurav-chandra** [dnKaratzas/android-inapp-update#1]
Hey, I am a hybrid developer and I am looking for a plugin for cordova which does exactly what your library does. If you have extra time, can you make a cordova plugin? I will help in testing and publishing to npm and can help with the xml or JavaScript. 

I don't know java or kotlin so I cannot do it myself. Here is the link to official cordova plugin guide https://cordova.apache.org/docs/en/latest/guide/hybrid/plugins/

If you can write the java part and put it in the repo, i can do the rest of the stuff and publish it in your name. 

Thanks.

**Comment by dnKaratzas** [comment]
I will check it and will inform you.
