### ISSUE TITLE
In App Updater not working properly

### ISSUE THREAD

**Issue by thomasp7983** [dnKaratzas/android-inapp-update#5]
Hi,

I am using InAppUpdater mentioned by you. 

This is absolutely working fine. 

But the problem which I have identified is "App is able to show the in app update when we open Google Play Store and look for updates".

App is not showing in app update until and unless we open Google play store and look for updates. 

I have created a Alpha Release and tested with some users before going live. 

Please let me know if there is any other way without opening GPS. 

Thank you.

**Comment by lucazin** [comment]
Hey man this happen with me again..

Im stucked in this problem

**Comment by dnKaratzas** [comment]
Updated the Core Play library to the latest version. Cannot test it right now. If you can please check if the update fixed this issue.

**Comment by thomasp7983** [comment]
Let me test it and update you.

**Comment by thomasp7983** [comment]
It is still not working... 

Same thing continues.

1. It is not showing any updates in the app.
2. Open GPS and check for updates
3. Close App
4. Open App and it shows update

**Comment by dnKaratzas** [comment]
I am using the lib to my application. It seems that PlayStore fetches periodically for updates. So the users at some time will get the notified for the update. It seems that can't be instant. I will research it in few days.

**Comment by thomasp7983** [comment]
My update is live from past 18 hours... App doesnt show update.

Will wait for few more dayd

**Comment by dnKaratzas** [comment]
That seems really strange. Opened also the PlayStore?

**Comment by thomasp7983** [comment]
If I open playstore, it is working fine.

**Comment by charlizesmith** [comment]
Does anyone get the solution for the issue? please reply. I am also not able to find a solution.

**Comment by dnKaratzas** [comment]
It seems that in order for the library to find an update we have to open PlayStore in order to fetch app updates. Unfortunately this is a bug on PlayServices itself.

**Comment by dnKaratzas** [comment]
It's a normal behavior. See #6

**Comment by VuManhHung97** [comment]
I am also having this problem. how to fix it?

**Comment by shekhar12020** [comment]
Put below broadcast to send heartbeat to fcm on every launch:

        sendBroadcast(new Intent("com.google.android.intent.action.GTALK_HEARTBEAT"));
        sendBroadcast(new Intent("com.google.android.intent.action.MCS_HEARTBEAT"));

It's working for me.
